Some tidying-up and some new funcitonality
tolitius/chazel pull request #7
Opened 2020-04-08 15:09 UTC by jimpil

Hi there,

First of all many thanks for your work on this ;)
Here is a PR that does a major cleanup, gets rid of reflection (there were more than 50 reflective calls!), swaps `cheshire` for `clojure.data.json` (also removes wallhack), and adds a new `ids.clj` namespace for dealing with ID-generation (pretty basic stuff).

Let me know if you're interested :) 

Kind regards,

2020-04-09 19:56 UTC, tolitius requested changes

2020-04-09 19:56 UTC, tolitius commented on src/chazel/core.clj
> +   (println group-name group-password )
let's not _print_ creds

2020-04-09 19:58 UTC, tolitius commented
:metal: thanks a lot. this is _a lot of_ cleanup )
did you repl / test the functions you modified?

2020-04-10 08:41 UTC, jimpil commented on src/chazel/core.clj
> +   (println group-name group-password )
oops!

2020-04-10 08:43 UTC, jimpil commented
Hi there,

I've run most of the code shown in the README and I can confirm it works. If you happen to have 5-10 minutes to spend using it in a real project - that would be awesome :).

2020-04-29 02:04 UTC, tolitius commented
I unfortunately do not have a prod like hazelcast env at the moment.
I did do some smoke testing. And since you have not really changed the _features_ besides the `IdGenerator` (thank you) it looks good.

could add some documentation about the `IdGenerator` so other people could find it easier?

I will merge this for now, since this code is written over the years and did collect some tech dept that you sliced and diced, hence it is definitely better than it was.

2020-04-29 02:05 UTC, merged

2020-04-29 02:07 UTC, tolitius commented
it now lives in `[chazel "0.1.20"]`